// <auto-generated />
using System;
using EnglishCenterManagement.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnglishCenterManagement.Models.Migrations
{
    [DbContext(typeof(EnglishCenterDbContext))]
    partial class EnglishCenterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("date")
                        .HasColumnName("create_at");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit")
                        .HasColumnName("gender");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsStudentManager")
                        .HasColumnType("bit")
                        .HasColumnName("is_student_manager");

                    b.Property<bool>("IsSuper")
                        .HasColumnType("bit")
                        .HasColumnName("is_super");

                    b.Property<bool>("IsTeacherManager")
                        .HasColumnType("bit")
                        .HasColumnName("is_teacher_manager");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("phone_number");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18, 3)")
                        .HasColumnName("salary");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("date")
                        .HasColumnName("update_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("user_name");

                    b.HasKey("AdminId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("admins", (string)null);
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("class_code");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("class_name");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("date")
                        .HasColumnName("create_at");

                    b.Property<int>("CurrentStudent")
                        .HasColumnType("int")
                        .HasColumnName("current_student");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int>("MaxStudent")
                        .HasColumnType("int")
                        .HasColumnName("max_student");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("note");

                    b.Property<string>("OnlineMeetingLink")
                        .HasMaxLength(1000)
                        .HasColumnType("text")
                        .HasColumnName("online_meeting_link");

                    b.Property<int>("Shift")
                        .HasColumnType("int")
                        .HasColumnName("shift");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("date")
                        .HasColumnName("update_at");

                    b.HasKey("ClassId");

                    b.ToTable("class", (string)null);
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.ClassCourse", b =>
                {
                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.HasKey("ClassId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("class_course", (string)null);
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.CommuneDistrict", b =>
                {
                    b.Property<int>("CommuneDistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("commune_district_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommuneDistrictId"));

                    b.Property<string>("CommuneDistrictName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("commune_district");

                    b.Property<int>("ProvinceCityId")
                        .HasColumnType("int")
                        .HasColumnName("province_city_id");

                    b.HasKey("CommuneDistrictId");

                    b.HasIndex("ProvinceCityId");

                    b.ToTable("commune_district", (string)null);
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("AvatarLink")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("avatar_link");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("course_code");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("course_name");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<int>("NumberSessions")
                        .HasColumnType("int")
                        .HasColumnName("number_sessions");

                    b.Property<decimal>("TutitionFee")
                        .HasColumnType("decimal(18, 3)")
                        .HasColumnName("tutition_fee");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at");

                    b.Property<string>("level")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("level");

                    b.HasKey("CourseId");

                    b.ToTable("course", (string)null);
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.ExamType", b =>
                {
                    b.Property<int>("ExamTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamTypeId"));

                    b.Property<string>("ExamTypeCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("exam_result_code");

                    b.Property<string>("ExamTypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("exam_result_name");

                    b.HasKey("ExamTypeId");

                    b.ToTable("exam_type", (string)null);
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("exercise_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExerciseId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("ImageLink")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("image_link");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("note");

                    b.Property<string>("Suggest")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("suggest");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("topic");

                    b.HasKey("ExerciseId");

                    b.HasIndex("TeacherId");

                    b.ToTable("exercise", (string)null);
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.Expertise", b =>
                {
                    b.Property<int>("ExpertiseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpertiseId"));

                    b.Property<string>("ExpertiseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("expertise_name");

                    b.HasKey("ExpertiseId");

                    b.ToTable("expertise", (string)null);
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.ExpertiseTeacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id");

                    b.Property<int>("ExpertiseID")
                        .HasColumnType("integer")
                        .HasColumnName("expertise_id");

                    b.HasKey("TeacherId", "ExpertiseID");

                    b.HasIndex("ExpertiseID");

                    b.ToTable("expertise_teacher", (string)null);
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.ProvinceCity", b =>
                {
                    b.Property<int>("ProvinceCityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("province_city_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceCityId"));

                    b.Property<string>("ProvinceCityName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("province_city_name");

                    b.HasKey("ProvinceCityId");

                    b.ToTable("province_city", (string)null);
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.Receipt", b =>
                {
                    b.Property<int>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("receipt_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceiptId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("payment_date");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("payment_method");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("ReceiptId");

                    b.HasIndex("StudentId", "CourseId")
                        .IsUnique();

                    b.ToTable("receipt", (string)null);
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.ResultExam", b =>
                {
                    b.Property<int>("ResultExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("result_exam_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultExamId"));

                    b.Property<int>("ExamTypeId")
                        .HasColumnType("int");

                    b.Property<double>("ResultListening")
                        .HasColumnType("float")
                        .HasColumnName("result_listening");

                    b.Property<double>("ResultReading")
                        .HasColumnType("float")
                        .HasColumnName("result_reading");

                    b.Property<double>("ResultSpeaking")
                        .HasColumnType("float")
                        .HasColumnName("result_speaking");

                    b.Property<double>("ResultWriting")
                        .HasColumnType("float")
                        .HasColumnName("result_writing");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.HasKey("ResultExamId");

                    b.HasIndex("ExamTypeId");

                    b.HasIndex("StudentId");

                    b.ToTable("result_exam", (string)null);
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("date")
                        .HasColumnName("creat_at");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit")
                        .HasColumnName("gender");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PhoneNumberOfParents")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("phone_number_of_parents");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("date")
                        .HasColumnName("update_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("user_name");

                    b.HasKey("StudentId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("students", (string)null);

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Address = "TP.HCM",
                            CreateAt = new DateTime(2025, 10, 15, 17, 3, 7, 781, DateTimeKind.Local).AddTicks(8753),
                            DateOfBirth = new DateOnly(2004, 5, 10),
                            Email = "vana@gmail.com",
                            FullName = "Nguyễn Văn A",
                            Gender = true,
                            IsActive = true,
                            Password = "123456",
                            PhoneNumber = "0911111111",
                            PhoneNumberOfParents = "0981111111",
                            UpdateAt = new DateTime(2025, 10, 15, 17, 3, 7, 781, DateTimeKind.Local).AddTicks(8771),
                            UserName = "nguyenvana"
                        },
                        new
                        {
                            StudentId = 2,
                            Address = "Đồng Nai",
                            CreateAt = new DateTime(2025, 10, 15, 17, 3, 7, 781, DateTimeKind.Local).AddTicks(8775),
                            DateOfBirth = new DateOnly(2003, 8, 25),
                            Email = "thib@gmail.com",
                            FullName = "Trần Thị B",
                            Gender = false,
                            IsActive = true,
                            Password = "123456",
                            PhoneNumber = "0912222222",
                            PhoneNumberOfParents = "0982222222",
                            UpdateAt = new DateTime(2025, 10, 15, 17, 3, 7, 781, DateTimeKind.Local).AddTicks(8776),
                            UserName = "tranthib"
                        },
                        new
                        {
                            StudentId = 3,
                            Address = "Bình Dương",
                            CreateAt = new DateTime(2025, 10, 15, 17, 3, 7, 781, DateTimeKind.Local).AddTicks(8779),
                            DateOfBirth = new DateOnly(2004, 1, 17),
                            Email = "vanc@gmail.com",
                            FullName = "Lê Văn C",
                            Gender = true,
                            IsActive = true,
                            Password = "123456",
                            PhoneNumber = "0913333333",
                            PhoneNumberOfParents = "0983333333",
                            UpdateAt = new DateTime(2025, 10, 15, 17, 3, 7, 781, DateTimeKind.Local).AddTicks(8779),
                            UserName = "levanc"
                        });
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.StudentAttendance", b =>
                {
                    b.Property<int>("StudentAttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("student_attendance_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentAttendanceId"));

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("date")
                        .HasColumnName("attendance_date");

                    b.Property<TimeSpan?>("CheckInTime")
                        .HasColumnType("time")
                        .HasColumnName("check_in_time");

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("date")
                        .HasColumnName("create_at");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("date")
                        .HasColumnName("update_at");

                    b.HasKey("StudentAttendanceId");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.ToTable("student_attendance", (string)null);
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.StudentClass", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.HasKey("StudentId", "ClassId");

                    b.HasIndex("ClassId");

                    b.ToTable("student_class", (string)null);
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.StudentCourse", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DicountValue")
                        .HasColumnType("decimal(10, 3)")
                        .HasColumnName("discount_value");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("discount_type");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("student_course", (string)null);
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.StudentExercise", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<string>("AnswerLink")
                        .HasColumnType("text")
                        .HasColumnName("answer_link");

                    b.Property<string>("CommentOfTeacher")
                        .HasColumnType("text")
                        .HasColumnName("comment_of_teacher");

                    b.Property<string>("CommentPrivateOfStudent")
                        .HasColumnType("text")
                        .HasColumnName("comment_private_of_student");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<double?>("Score")
                        .HasColumnType("float")
                        .HasColumnName("score");

                    b.HasKey("StudentId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("student_exercise", (string)null);
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.Teacher", b =>
                {
                    b.Property<int>("TeacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("date")
                        .HasColumnName("create_at");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit")
                        .HasColumnName("gender");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("phone_number");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18, 3)")
                        .HasColumnName("salary");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("date")
                        .HasColumnName("update_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("user_name");

                    b.HasKey("TeacherID");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("teachers", (string)null);

                    b.HasData(
                        new
                        {
                            TeacherID = 1,
                            Address = "Hà Nội",
                            CreateAt = new DateTime(2025, 10, 15, 17, 3, 7, 783, DateTimeKind.Local).AddTicks(9600),
                            DateOfBirth = new DateOnly(1990, 5, 12),
                            Email = "nguyenvana@example.com",
                            FullName = "Nguyễn Văn A",
                            Gender = true,
                            IsActive = true,
                            Password = "123456",
                            PhoneNumber = "0912345678",
                            Salary = 15000000m,
                            UpdateAt = new DateTime(2025, 10, 15, 17, 3, 7, 783, DateTimeKind.Local).AddTicks(9603),
                            UserName = "nguyenvana"
                        },
                        new
                        {
                            TeacherID = 2,
                            Address = "TP.HCM",
                            CreateAt = new DateTime(2025, 10, 15, 17, 3, 7, 783, DateTimeKind.Local).AddTicks(9606),
                            DateOfBirth = new DateOnly(1993, 8, 20),
                            Email = "tranthib@example.com",
                            FullName = "Trần Thị B",
                            Gender = false,
                            IsActive = true,
                            Password = "abcdef",
                            PhoneNumber = "0987654321",
                            Salary = 18000000m,
                            UpdateAt = new DateTime(2025, 10, 15, 17, 3, 7, 783, DateTimeKind.Local).AddTicks(9607),
                            UserName = "tranthib"
                        },
                        new
                        {
                            TeacherID = 3,
                            Address = "Đà Nẵng",
                            CreateAt = new DateTime(2025, 10, 15, 17, 3, 7, 783, DateTimeKind.Local).AddTicks(9610),
                            DateOfBirth = new DateOnly(1988, 2, 15),
                            Email = "lequangc@example.com",
                            FullName = "Lê Quang C",
                            Gender = true,
                            IsActive = true,
                            Password = "qwerty",
                            PhoneNumber = "0978123456",
                            Salary = 20000000m,
                            UpdateAt = new DateTime(2025, 10, 15, 17, 3, 7, 783, DateTimeKind.Local).AddTicks(9610),
                            UserName = "lequangc"
                        });
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.TeacherAttendance", b =>
                {
                    b.Property<int>("TeacherAttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("teacher_attendance_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherAttendanceId"));

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("date")
                        .HasColumnName("attendance_date");

                    b.Property<TimeSpan?>("CheckInTime")
                        .HasColumnType("time")
                        .HasColumnName("check_in_time");

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("date")
                        .HasColumnName("create_at");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("date")
                        .HasColumnName("update_at");

                    b.HasKey("TeacherAttendanceId");

                    b.HasIndex("ClassId");

                    b.HasIndex("TeacherId");

                    b.ToTable("teacher_attendance", (string)null);
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.TeacherClass", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.HasKey("TeacherId", "ClassId");

                    b.HasIndex("ClassId");

                    b.ToTable("teacher_class", (string)null);
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.TeacherCourse", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.HasKey("TeacherId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("teacher_course", (string)null);
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.ClassCourse", b =>
                {
                    b.HasOne("EnglishCenterManagement.Models.Entities.Class", "Class")
                        .WithMany("ClassCourses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishCenterManagement.Models.Entities.Course", "Course")
                        .WithMany("ClassCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.CommuneDistrict", b =>
                {
                    b.HasOne("EnglishCenterManagement.Models.Entities.ProvinceCity", "ProvinceCity")
                        .WithMany("CommuneDistricts")
                        .HasForeignKey("ProvinceCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProvinceCity");
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.Exercise", b =>
                {
                    b.HasOne("EnglishCenterManagement.Models.Entities.Teacher", "Teacher")
                        .WithMany("Exercises")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.ExpertiseTeacher", b =>
                {
                    b.HasOne("EnglishCenterManagement.Models.Entities.Expertise", "Expertise")
                        .WithMany("ExpertiseTeachers")
                        .HasForeignKey("ExpertiseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishCenterManagement.Models.Entities.Teacher", "Teacher")
                        .WithMany("expertiseTeachers")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expertise");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.Receipt", b =>
                {
                    b.HasOne("EnglishCenterManagement.Models.Entities.StudentCourse", "StudentCourse")
                        .WithOne("Receipt")
                        .HasForeignKey("EnglishCenterManagement.Models.Entities.Receipt", "StudentId", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentCourse");
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.ResultExam", b =>
                {
                    b.HasOne("EnglishCenterManagement.Models.Entities.ExamType", "ExamType")
                        .WithMany("ResultExams")
                        .HasForeignKey("ExamTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnglishCenterManagement.Models.Entities.Student", "Student")
                        .WithMany("ResultExams")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamType");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.StudentAttendance", b =>
                {
                    b.HasOne("EnglishCenterManagement.Models.Entities.Class", "Class")
                        .WithMany("StudentAttendances")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishCenterManagement.Models.Entities.Student", "Student")
                        .WithMany("StudentAttendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.StudentClass", b =>
                {
                    b.HasOne("EnglishCenterManagement.Models.Entities.Class", "Class")
                        .WithMany("StudentClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishCenterManagement.Models.Entities.Student", "Student")
                        .WithMany("StudentClasses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.StudentCourse", b =>
                {
                    b.HasOne("EnglishCenterManagement.Models.Entities.Course", "Course")
                        .WithMany("StudentCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishCenterManagement.Models.Entities.Student", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.StudentExercise", b =>
                {
                    b.HasOne("EnglishCenterManagement.Models.Entities.Exercise", "Exercise")
                        .WithMany("StudentExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishCenterManagement.Models.Entities.Student", "Student")
                        .WithMany("StudentExercises")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.TeacherAttendance", b =>
                {
                    b.HasOne("EnglishCenterManagement.Models.Entities.Class", "Class")
                        .WithMany("TeacherAttendances")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishCenterManagement.Models.Entities.Teacher", "Teacher")
                        .WithMany("TeacherAttendances")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.TeacherClass", b =>
                {
                    b.HasOne("EnglishCenterManagement.Models.Entities.Class", "Class")
                        .WithMany("TeacherClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishCenterManagement.Models.Entities.Teacher", "Teacher")
                        .WithMany("TeacherClasses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.TeacherCourse", b =>
                {
                    b.HasOne("EnglishCenterManagement.Models.Entities.Course", "Course")
                        .WithMany("TeacherCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishCenterManagement.Models.Entities.Teacher", "Teacher")
                        .WithMany("TeacherCourses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.Class", b =>
                {
                    b.Navigation("ClassCourses");

                    b.Navigation("StudentAttendances");

                    b.Navigation("StudentClasses");

                    b.Navigation("TeacherAttendances");

                    b.Navigation("TeacherClasses");
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.Course", b =>
                {
                    b.Navigation("ClassCourses");

                    b.Navigation("StudentCourses");

                    b.Navigation("TeacherCourses");
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.ExamType", b =>
                {
                    b.Navigation("ResultExams");
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.Exercise", b =>
                {
                    b.Navigation("StudentExercises");
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.Expertise", b =>
                {
                    b.Navigation("ExpertiseTeachers");
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.ProvinceCity", b =>
                {
                    b.Navigation("CommuneDistricts");
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.Student", b =>
                {
                    b.Navigation("ResultExams");

                    b.Navigation("StudentAttendances");

                    b.Navigation("StudentClasses");

                    b.Navigation("StudentCourses");

                    b.Navigation("StudentExercises");
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.StudentCourse", b =>
                {
                    b.Navigation("Receipt")
                        .IsRequired();
                });

            modelBuilder.Entity("EnglishCenterManagement.Models.Entities.Teacher", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("TeacherAttendances");

                    b.Navigation("TeacherClasses");

                    b.Navigation("TeacherCourses");

                    b.Navigation("expertiseTeachers");
                });
#pragma warning restore 612, 618
        }
    }
}
